name: app

type: 'python:3.11'

disk: 2048

hooks:
    build: |
      pip install -r requirements.txt

web:
  commands:
    start: "gunicorn topicreport.wsgi:application"

mounts:
  '/static':
    source: local
    source_path: 'topicreport/core/static'