name: app

type: 'python:3.11'

disk: 2048

hooks:
    build: |
      pip install -r requirements.txt

web:
    upstream:
        socket_family: unix
    commands:
        start: "gunicorn -w 4 -b unix:$SOCKET topicreport.wsgi:application"

mounts:
  '/static':
    source: local
    source_path: 'topicreport/core/static'
