name: app

type: 'python:3.11'

disk: 2048

hooks:
  build: |
    python -m venv venv
    source venv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    python manage.py collectstatic --noinput

web:
  commands:
    start: "gunicorn topicreport.wsgi:application"

  locations:
    "/":
      passthru: true
    "/static":
      root: "static"
      expires: 1h
      allow: true
