name: app

type: 'python:3.11'

disk: 2048

web:
  commands:
    start: "gunicorn topicreport.wsgi:application"

mounts:
  '/static':
    source: local
    source_path: 'topicreport/core/static'

dependencies:
  python:
    requirements:
      file: requirements.txt
